<?php session_start(); ?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PokéSave Editor Admin</title>
<style>body{font-family:system-ui;margin:0;background:#f5f7fb;color:#111827}.wrap{max-width:900px;margin:40px auto;padding:0 18px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:24px;margin:18px 0}h1{margin:0 0 8px}h2{margin-top:0}label{display:block;font-size:13px;font-weight:700;margin:14px 0 6px}input[type=text],input[type=password],input[type=color]{width:100%;box-sizing:border-box;padding:11px;border:1px solid #d0d5dd;border-radius:9px}input[type=color]{height:44px;padding:3px}button{border:0;border-radius:9px;padding:11px 16px;background:#5b4cf6;color:white;font-weight:700;cursor:pointer}.row{display:grid;grid-template-columns:1fr 1fr;gap:16px}.checks label{display:flex;gap:9px;align-items:center;font-weight:600}.checks input{width:auto}.muted{color:#667085;font-size:13px}.hidden{display:none}.msg{padding:10px;border-radius:8px;background:#eef2ff;margin-top:12px}.danger{color:#b42318}@media(max-width:700px){.row{grid-template-columns:1fr}}</style></head><body><div class="wrap"><div class="card"><h1>PokéSave Editor Admin</h1><p class="muted">Branding and UI settings. The editor automatically detects its own installation folder, so moving /saveeditor/ to another path does not require a rebuild.</p><div id="login"><label>Admin password</label><input id="pw" type="password"><br><br><button onclick="login()">Sign in</button><div id="loginmsg" class="danger"></div></div></div>
<div id="panel" class="hidden"><div class="card"><h2>Branding</h2><div class="row"><div><label>Site name</label><input id="siteName" type="text"></div><div><label>Header text</label><input id="headerText" type="text"></div></div><label>Footer text</label><input id="footerText" type="text"><label>Logo</label><input id="logo" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><br><br><button onclick="uploadLogo()">Upload logo</button><span id="logoMsg" class="muted"></span></div>
<div class="card"><h2>Colors</h2><div class="row"><div><label>Primary</label><input id="primaryColor" type="color"></div><div><label>Primary hover</label><input id="primaryHoverColor" type="color"></div><div><label>Button</label><input id="buttonColor" type="color"></div><div><label>Button hover</label><input id="buttonHoverColor" type="color"></div><div><label>Background</label><input id="backgroundColor" type="color"></div><div><label>Surface</label><input id="surfaceColor" type="color"></div><div><label>Text</label><input id="textColor" type="color"></div><div><label>Muted text</label><input id="mutedColor" type="color"></div><div><label>Border</label><input id="borderColor" type="color"></div></div></div>
<div class="card"><h2>Navigation</h2><div class="checks"><label><input id="showPlugins" type="checkbox"> Show Plugins</label><label><input id="showAnalytics" type="checkbox"> Show Analytics</label><label><input id="showSave" type="checkbox"> Show Save</label><label><input id="showOpen" type="checkbox"> Show Open</label><label><input id="showSource" type="checkbox"> Show Source link</label></div></div>
<div class="card"><button onclick="save()">Save settings</button> <button onclick="logout()">Log out</button><div id="msg" class="msg"></div></div></div></div>
<script>
const fields=['siteName','headerText','footerText','primaryColor','primaryHoverColor','buttonColor','buttonHoverColor','backgroundColor','surfaceColor','textColor','mutedColor','borderColor'];
async function api(url,opt={}){let r=await fetch(url,opt);let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function login(){try{await api('api/login.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.getElementById('pw').value})});document.getElementById('login').classList.add('hidden');document.getElementById('panel').classList.remove('hidden');load()}catch(e){document.getElementById('loginmsg').textContent=e.message}}
async function load(){let c=await api('api/config.php');fields.forEach(x=>document.getElementById(x).value=c[x]||'');['showPlugins','showAnalytics','showSave','showOpen','showSource'].forEach(x=>document.getElementById(x).checked=!!c[x])}
async function save(){let c={};fields.forEach(x=>c[x]=document.getElementById(x).value);['showPlugins','showAnalytics','showSave','showOpen','showSource'].forEach(x=>c[x]=document.getElementById(x).checked);try{await api('api/save.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)});document.getElementById('msg').textContent='Saved. Refresh the editor to apply the changes.'}catch(e){document.getElementById('msg').textContent=e.message}}
async function uploadLogo(){let f=document.getElementById('logo').files[0];if(!f)return;let fd=new FormData();fd.append('logo',f);try{await api('api/upload.php',{method:'POST',body:fd});document.getElementById('logoMsg').textContent=' Uploaded.';load()}catch(e){document.getElementById('logoMsg').textContent=' '+e.message}}
async function logout(){await api('api/logout.php');location.reload()}
</script></body></html>
